language: node_js
sudo: false

node_js:
  - "8"
  - "10"
  - "11"

script:
  - NODE_VERSION=$(echo $(node -v) | cut -c2-10) npm run test

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.0.4/gnatsd-v1.0.4-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v1.0.4-linux-amd64 gnatsd
